Capstone-2020/PetUniverse/WPFPresentation/Models/ApplicantListViewModel.cs
using DataTransferObjects;
using System.Collections.Generic;

namespace WPFPresentation.Models
{
    /// <summary>
    /// CREATED BY: Derek Taylor
    /// DATE: 2/14/2020
    /// CHECKED BY: Ryan Morganti
    /// 
    /// This class is the ViewModel of the Applicant List
    /// </summary>
    /// <remarks>
    /// UPDATED BY: NA
    /// UPDATE DATE: NA
    /// CHANGE: NA
    /// 
    /// </remarks>
    public class ApplicantListViewModel
    {
        /// <summary>
        /// CREATED BY: Derek Taylor
        /// DATE: 2/14/2020
        /// CHECKED BY: Ryan Morganti
        /// 
        /// This class tests the LogManager Class
        /// </summary>
        /// <remarks>
        /// UPDATED BY: NA
        /// UPDATE DATE: NA
        /// CHANGE: NA
        /// 
        /// </remarks>
        public List<Applicant> Applicants { get; set; }
    }
}

Capstone-2020/PetUniverse/WPFPresentation/Controllers/CareersController.cs
using LogicLayer;
using LogicLayerInterfaces;
using System;
using System.Linq;
using System.Web.Mvc;
using WPFPresentation.Models;

namespace WPFPresentation.Controllers
{
    /// <summary>
    /// NAME : Derek Taylor
    /// DATE: 2/14/2020
    /// CHECKED BY:
    /// 
    /// This class is the controller for Applications and Applicants.
    /// </summary>
    /// <remarks>
    /// UPDATED BY: NA
    /// UPDATE DATE: NA
    /// CHANGE: NA
    /// 
    /// </remarks>
    public class CareersController : Controller
    {
        private IApplicantManager _applicantManager;
        /// <summary>
        /// NAME : Derek Taylor
        /// DATE: 2/14/2020
        /// CHECKED BY:
        /// 
        /// This method is the constructor for the controller
        /// </summary>
        /// <remarks>
        /// UPDATED BY: NA
        /// UPDATE DATE: NA
        /// CHANGE: NA
        /// 
        /// </remarks>
        public CareersController()
        {
            _applicantManager = new ApplicantManager();
        }
        /// <summary>
        /// NAME : Derek Taylor
        /// DATE: 2/14/2020
        /// CHECKED BY:
        /// 
        /// This method is a constructor for the controller
        /// </summary>
        /// <remarks>
        /// UPDATED BY: NA
        /// UPDATE DATE: NA
        /// CHANGE: NA
        /// 
        /// </remarks>
        public CareersController(IApplicantManager applicantManager)
        {
            _applicantManager = applicantManager;
        }
        /// <summary>
        /// NAME : Derek Taylor
        /// DATE: 2/14/2020
        /// CHECKED BY:
        /// 
        /// This Method returns the ViewList of Applicants and allows for sorting based on
        /// the last name of the Applicant.
        /// </summary>
        /// <remarks>
        /// UPDATED BY: NA
        /// UPDATE DATE: NA
        /// CHANGE: NA
        /// 
        /// </remarks>
        /// <returns>ViewList of applicants</returns>
        public ActionResult ApplicantList(string sortOrder)
        {
            ViewBag.NameSortParam = String.IsNullOrEmpty(sortOrder) ? "name_descending" : "";
            var applicants = from a in _applicantManager.RetrieveApplicants()
                             select a;
            switch (sortOrder)
            {
                case "name_descending":
                    applicants = applicants.OrderByDescending(a => a.LastName);
                    break;
                default:
                    applicants = applicants.OrderBy(a => a.LastName);
                    break;
            }
            ApplicantListViewModel viewModel = new ApplicantListViewModel
            {
                Applicants = applicants.ToList()
            };
            return View(viewModel);
        }

        /// <summary>
        /// Creator : Ryan Morganti
        /// Created: 2020/03/19
        /// Approver: Derek Taylor
        /// 
        /// This Method returns the Index Page View, which allows for the navigation to other views held by this controller
        /// </summary>
        /// <remarks>
        /// Updator: NA
        /// Updated: NA
        /// Update: NA
        /// 
        /// </remarks>
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Creator : Ryan Morganti
        /// Created: 2020/03/19
        /// Approver:
        /// 
        /// This Method returns the Positions Page View, which allows the user to view a list of positions
        /// This list will change depending on whether the user is authorized to activate/deactivate/create/deleted OR
        /// is browsing open positions to apply for
        /// </summary>
        /// <remarks>
        /// Updator: NA
        /// Updated: NA
        /// Update: NA
        /// 
        /// </remarks>
        public ActionResult Positions()
        {
            var positions = _applicantManager.RetrieveAllPositions();
            return View(positions);
        }
    }
}

Capstone-2020/PetUniverse/WPFPresentation/Views/Careers/ApplicantList.cshtml
@model WPFPresentation.Models.ApplicantListViewModel

@{
    ViewBag.Title = "Applicants";
    Layout = "~/views/Shared/_InternalLayout.cshtml";
}
<header><h1>Applicants</h1></header>
<table class="table table-hover table-striped">
    <thead>
        <tr>
            <th>@Html.ActionLink("Last Name, First Name", "ApplicantList", new { sortOrder = ViewBag.NameSortParam })</th>
            <th>Email</th>
            <th>Phone Number</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var applicant in Model.Applicants)
        {
            <tr>
                <td>@applicant.LastName , @applicant.FirstName</td>
                <td>@applicant.Email</td>
                <td>@applicant.PhoneNumber</td>
                <td>
                    @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Interview", "Interview", new { /* id=item.PrimaryKey */ })
                </td>
            </tr>
        }
    </tbody>
</table>

Capstone-2020/PetUniverse/WPFPresentation/Views/Careers/Index.cshtml
@{
    ViewBag.Title = "PetUniverse Careers";
}

<h2>Careers at Pet Universe!</h2>
<p>Placeholder text for welcoming to the Careers landing page</p>

<button>
    @Html.ActionLink("Available Positions", "Positions", "Careers")
</button>

<button>
    @Html.ActionLink("Submitted Applications", "ApplicantList", "Careers")
</button>

Capstone-2020/PetUniverse/WPFPresentation/Views/Careers/Positions.cshtml
@model IEnumerable<DataTransferObjects.JobListing>

@{
    ViewBag.Title = "Positions";
}

<h2>Positions</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Position)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Benefits)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Requirements)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartingWage)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Responsibilities)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Active)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Position)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Benefits)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Requirements)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartingWage)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Responsibilities)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Active)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.JobListingID }) |
            @Html.ActionLink("Details", "Details", new { id=item.JobListingID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.JobListingID })
        </td>
    </tr>
}

</table>