Capstone-2020/PetUniverse/WPFPresentation/Controllers/DonationsController.cs
using LogicLayer;
using LogicLayerInterfaces;
using DataTransferObjects;
using System.Web.Mvc;
using System.Web;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity;
using System.Collections.Generic;
using System.Linq;

namespace WPFPresentation.Controllers
{
    public class DonationsController : Controller
    {
        private IDonationManager _donationManager;

        public DonationsController()
        {
            _donationManager = new DonationManager();
        }


        // GET: Donations
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Creator: Steve Coonrod
        /// Created: 2020/04/15
        /// Approver: Matt Deaton
        ///
        /// ActionResult Method to display the FAQ list
        /// </summary>
        /// <remarks>
        /// 
        /// Updator:
        /// Updated:
        /// Update:
        ///
        /// </remarks>
        /// <returns></returns>
        public ActionResult DonationFAQ()
        {
            return View();
        }

        /// <summary>
        /// Creator: Ryan Morganti
        /// Created: 2020/04/05
        /// Approver: Matt Deaton
        ///
        /// ActionResult Method to load a ListView of the Past Donations received by the
        /// PetUniverse Shelter
        /// </summary>
        /// <remarks>
        /// Updator:
        /// Updated:
        /// Update:
        ///
        /// </remarks>
        [Authorize]
        public ActionResult PastDonations()
        {
            ViewBag.Title = "PastDonations";
            var donations = _donationManager.RetrieveAllDonationsFromPastYear();
            return View(donations);
        }

        /// <summary>
        /// Creator: Ryan Morganti
        /// Created: 2020/04/16
        /// Approver: Derek Taylor
        ///
        /// ActionResult Method to load a Form for setting up a Recurring Donation linked
        /// to the user account currently logged in.
        /// </summary>
        /// <remarks>
        /// Updator:
        /// Updated:
        /// Update:
        ///
        /// </remarks>
        [Authorize]
        public ActionResult NewRecurringDonation()
        {
            //ViewBag.IntervalList = GetIntervalList();
            ViewBag.Title = "NewRecurringDonation";
            return View(new RecurringDonationVM());
        }

        /// <summary>
        /// Creator: Ryan Morganti
        /// Created: 2020/04/16
        /// Approver: Derek Taylor
        ///
        /// ActionResult Method to POST a newly set Recurring Donation for the current user.
        /// </summary>
        /// <remarks>
        /// Updator: Ryan Morganti
        /// Updated: 2020/04/29
        /// Update: Added Identity system to link current user
        ///
        /// </remarks>
        [Authorize]
        [HttpPost]
        public ActionResult NewRecurringDonation(RecurringDonationVM recurringDonation)
        {
            int result = 0;
            
            ApplicationUserManager userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            var user = userManager.FindById(User.Identity.GetUserId());
            recurringDonation.UserName = user.Email;
            if (ModelState.IsValid)
            {
                try
                {
                    result = _donationManager.CreateNewRecurringDonation(recurringDonation);
                    if (result == 1)
                    {
                        return RedirectToAction("Index");
                    }
                }
                catch
                {
                    return View();
                }

            }
            return View();
        }

        /// <summary>
        /// Creator: Ryan Morganti
        /// Created: 2020/04/29
        /// Approver: Derek Taylor
        ///
        /// ActionResult Method to load a ListView of active Recurring Donations
        /// linked to the current user account.
        /// </summary>
        /// <remarks>
        /// Updator:
        /// Updated:
        /// Update:
        ///
        /// </remarks>
        [Authorize]
        public ActionResult ActiveDonations()
        {
            ApplicationUserManager userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            var user = userManager.FindById(User.Identity.GetUserId());
            var username = user.Email;
            List<RecurringDonationVM> donations = _donationManager.RetrieveAllRecurringDonationsByUser(username);
            var activeDonations = (from d in donations
                                   where d.Active == true
                                   select d).ToList();
            foreach(var d in activeDonations)
            {
                if(d.Interval < 3)
                {
                    d.IntervalVM = d.Interval > 1 ? "Monthly" : "Weekly";
                } else
                {
                    d.IntervalVM = "Yearly";
                }
                
            }
            return View(activeDonations);
        }

        /// <summary>
        /// Creator: Ryan Morganti
        /// Created: 2020/04/29
        /// Approver: Derek Taylor
        ///
        /// ActionResult Method to Confirm Cancellation of an active
        /// Recurring Donation for the current user account.
        /// </summary>
        /// <remarks>
        /// Updator:
        /// Updated:
        /// Update:
        ///
        /// </remarks>
        [Authorize]
        public ActionResult CancelRecurringDonation(int id)
        {
            var donation = _donationManager.RetrieveRecurringDonationByID(id);
            return View(donation);
        }

        /// <summary>
        /// Creator: Ryan Morganti
        /// Created: 2020/04/29
        /// Approver: Derek Taylor
        ///
        /// ActionResult Method to POST confirmation of recurring donation cancellation
        /// for the current user account.  Will redirect back to the active recurring donation view
        /// if successful.
        /// </summary>
        /// <remarks>
        /// Updator:
        /// Updated:
        /// Update:
        ///
        /// </remarks>
        [Authorize]
        [HttpPost]
        public ActionResult CancelRecurringDonation(int id, FormCollection collection)
        {
            int result = 0;
            if (ModelState.IsValid)
            {
                try
                {
                    result = _donationManager.DeleteRecurringDonation(id);
                    if (result == 1)
                    {
                        return RedirectToAction("ActiveDonations");
                    }
                }
                catch
                {
                    return View();
                }
            }
            return View();
        }
    }
}

Capstone-2020/PetUniverse/WPFPresentation/Views/Donations/ActiveDonations.cshtml
@model IEnumerable<DataTransferObjects.RecurringDonationVM>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DonationAmount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Interval)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.DonationAmount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IntervalVM)
        </td>
        <td>
            @Html.ActionLink("Cancel Recurring Donation", "CancelRecurringDonation", new { id = item.RecurringDonationID })
        </td>
    </tr>
}

</table>

Capstone-2020/PetUniverse/WPFPresentation/Views/Donations/CancelRecurringDonation.cshtml
@model DataTransferObjects.RecurringDonationVM

<h3>Are you sure you want to cancel this recurring donation?</h3>
<div>
    <h4>RecurringDonation</h4>
    <hr />
    <dl class="dl-horizontal">
        

        <dt>
            @Html.DisplayNameFor(model => model.DonationAmount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DonationAmount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Interval)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IntervalVM)
        </dd>

       

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="CancelRecurringDonation" class="btn btn-default"  /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Capstone-2020/PetUniverse/WPFPresentation/Views/Donations/DonationFAQ.cshtml
@{
	ViewBag.Title = "DonationFAQ";
	Layout = "~/Views/Shared/_InternalLayout.cshtml";
}
<head>
	<link href="~/Content/FAQ.css" rel="stylesheet" />
</head>

<div class="FAQTable">
	<div class="FAQTableHeader">
		<h2 style="color:orangered">Donation Frequently Asked Questions</h2>
	</div>
	<div class="FAQTable">
		<ul>
			<li>
				<p class="FAQquestion" style="color:orangered">Is my donation tax deductible?</p>
				<p class="FAQanswer">Yes, Pet Universe is a 501(c)3 tax-exempt organization, All donations are tax Deductible within the guidlines of U.S.law.</p>
			</li>
			<li>
				<p class="FAQquestion" style="color:orangered">Will I recieve a donation reciept for tax puropses?</p>
				<p class="FAQanswer">You will recieve an email for confirmation of your donation. This can be used as a donation reciept for your official records.</p>
			</li>
			<li>
				<p class="FAQquestion" style="color:orangered">How can I make changes to my monthly gift?</p>
				<p class="FAQanswer">Please email <a href="mailto:Donations@PetUniverse.com">Donations@PetUniverse.com</a> with your request and provide a phone number we can reach you at.</p>
			</li>
			<li>
				<p class="FAQquestion" style="color:orangered">Can I stop my monthly gift whenever I want?</p>
				<p class="FAQanswer">
					Absolutely! If you have a monthly gift through PayPal,
					you can cancel your gift by logging into your PayPal account. If you gave by credit card,
					please email us at <a href="mailto:Donations@PetUniverse.com">Donations@PetUniverse.com</a> and we’ll be happy to assist.
				</p>
			</li>
			<li>
				<p class="FAQquestion" style="color:orangered">Can I make a donation by mailing a check?</p>
				<p class="FAQanswer">
					Yes, if you prefer to donate by mail please send your check to:
					<br />
					<br />
					Pet Universe Donations<br />
					353 SomeStreet Cedar Rapids, IA 52402
				</p>
			</li>
		</ul>
	</div>
</div>

Capstone-2020/PetUniverse/WPFPresentation/Views/Donations/Index.cshtml
@{
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Donations</h1>

<h2>This is the landing page for the Donations Domain.</h2>

<p>Eventually this will look like an actual webpage.</p>

<button>
	@Html.ActionLink("Donations FAQ", "DonationFAQ", "Donations")
</button>

<button>
    @Html.ActionLink("View Past Donations", "PastDonations", "Donations")
</button>

Capstone-2020/PetUniverse/WPFPresentation/Views/Donations/NewRecurringDonation.cshtml
@model DataTransferObjects.RecurringDonationVM

@{
    ViewBag.Title = "NewRecurringDonation";
}

<h2>NewRecurringDonation</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>RecurringDonationViewModel</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.DonationAmount, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DonationAmount, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DonationAmount, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Interval, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <label>@Html.RadioButtonFor(model => model.Interval, 1) Weekly</label><br />
            <label>@Html.RadioButtonFor(model => model.Interval, 2) Monthly</label><br />
            <label>@Html.RadioButtonFor(model => model.Interval, 3) Yearly  </label><br />

            @Html.ValidationMessageFor(model => model.Interval, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BillingName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.BillingName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.BillingName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CardNumber, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CardNumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CardNumber, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ExpirationDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ExpirationDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ExpirationDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AddressLine1, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AddressLine1, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AddressLine1, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AddressLine2, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AddressLine2, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AddressLine2, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Zip, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Zip, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Zip, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Capstone-2020/PetUniverse/WPFPresentation/Views/Donations/PastDonations.cshtml
@model IEnumerable<DataTransferObjects.Donation>

@{
    ViewBag.Title = "PastDonations";
}

<h2>PastDonations</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Active)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TypeOfDonation)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateOfDonation)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DonationAmount)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Active)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TypeOfDonation)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateOfDonation)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DonationAmount)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>